version: '3.8'

services:
  job-applier:
    build: .
    container_name: ultimate-job-applier
    ports:
      - "7788:7788"    # Web interface (if needed)
      - "11434:11434"  # Ollama API
    volumes:
      - ./job_config.json:/app/job_config.json
      - ./data:/app/data
      - ollama_models:/root/.ollama
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - PYTHONPATH=/app/src
      - OLLAMA_HOST=0.0.0.0:11434
      - DISPLAY=${DISPLAY:-:0}
    stdin_open: true
    tty: true
    restart: unless-stopped
    # For GUI applications (browser automation)
    network_mode: host
    privileged: true

volumes:
  ollama_models:
    driver: local
